name: FronM11_CD

on:
  push:
    branches: "master"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.13.1'
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm run test

  deploy:
    name: Deploy to SFTP
    runs-on: ubuntu-latest
    needs: tests  # Solo despliega si las pruebas pasan
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'  # Solo en push a master, no en PRs

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.13.1'
    - name: Install Dependencies
      run: npm install
    - name: Build Project
      run: npm run build
      
    - name: Deploy to SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
         username: bbb7d2251d71441db5657b5d02376173
         server: us-east-1.sftpcloud.io
         password: eabCHQ260XWZmgTM5aHal1k1GDYPaqV5  # Descomenta si usas contraseña
         local-dir: ./dist/  # Sube el compilado dist
         server-dir: ./frontend/
